# bunfig.toml

name = "shift-scheduler-api"
type = "server"

[server]
port = 3000

[dependencies]
express = "^4.17.1"
sequelize = "^6.6.5"
mysql2 = "^2.3.3"
typescript = "^4.4.4"
@types/express = "^4.17.13"
@types/sequelize = "^4.28.10"
@types/node = "^16.11.7"

[devDependencies]
ts-node = "^10.4.0"
nodemon = "^2.0.12"